### ISSUE TITLE
jse-jumpbot: Local records not replaying

### ISSUE THREAD

**Issue by LapplandBro** [Jump-Academy/jse#33] opened 2023-08-20 13:57 UTC
```
L 08/20/2023 - 20:50:49: [SM] Exception reported: Invalid Handle 18d01f30 (error: 3)
L 08/20/2023 - 20:50:49: [SM] Blaming: jse_jumpbot.smx
L 08/20/2023 - 20:50:49: [SM] Call stack trace:
L 08/20/2023 - 20:50:49: [SM]   [0] ArrayList.Length.get
L 08/20/2023 - 20:50:49: [SM]   [1] Line 4050, C:\Build\jse\scripting\jse_jumpbot.sp::FindNearestRecording
L 08/20/2023 - 20:50:49: [SM]   [2] Line 2803, C:\Build\jse\scripting\jse_jumpbot.sp::cmdShowMe
```

The records are downloaded from the local repository, but they are not displayed to normal players - it says: no records.
Occurs with the Bubbles variable disabled.

**Comment by geominorai** [comment] 2023-08-20 14:05
I cannot seem to reproduce this error, even with `jse_jb_bubble = 0`.

Under what circumstances does this error happen?

**Comment by LapplandBro** [comment] 2023-08-20 14:11
That's a good question.
Wait for the video.

**Comment by LapplandBro** [comment] 2023-08-20 15:08
https://youtu.be/Kr_ZJCkdVLA

**Comment by geominorai** [comment] 2023-08-20 23:20
Thanks for the video and log.  In the future, please show the log right before reproducing the first error and immediately afterwards that error.  Seeing the log after a bunch of other error triggers makes it hard to pinpoint exactly where it started (since it can cause a cascade of related errors afterwards).

This bug seems related to bug #25 in that the main array list of recordings seems to have become invalid.

**Comment by LapplandBro** [comment] 2023-08-30 15:31
> Can you check if this bug persists after PR #35?

Everything works properly, no errors, even with bubbles.

**Comment by geominorai** [comment] 2023-08-30 21:44
Glad to hear that. I will go ahead and close this issue then.

**Closed** 2023-08-30 21:44 UTC
